import type { Metadata } from "next";
import { Cormorant_Garamond, Nunito } from "next/font/google";
import "./globals.css";
import { NotificationProvider } from "@/components/Notification";

const cormorantGaramond = Cormorant_Garamond({
  weight: "400",
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-cormorant-garamond",
});

const nunito = Nunito({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Pay N Print",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${cormorantGaramond.variable} ${nunito.variable} antialiased`}
      >
        <NotificationProvider>
          {children}
        </NotificationProvider>
      </body>
    </html>
  );
}
